services:
  azure-functions:
    build: .
    ports:
      - "8080:80"
    environment:
      - AzureWebJobsStorage=UseDevelopmentStorage=true
      - AzureWebJobsDashboard=UseDevelopmentStorage=true
      - MongoDB__ConnectionString=mongodb://mongodb:27017
      - Kafka__BootstrapServers=kafka1:9092,kafka2:9093,kafka3:9094
    depends_on:
      - mongodb
      - kafka-configuration-broker
      - kafka-rest-broker
      - kafka-worker-broker

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka-configuration-broker:
    image: 'confluentinc/cp-kafka:6.2.0'
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-rest-broker:
    image: 'confluentinc/cp-kafka:6.2.0'
    depends_on:
      - zookeeper
    ports:
      - '9093:9093'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-worker-broker:
    image: 'confluentinc/cp-kafka:6.2.0'
    depends_on:
      - zookeeper
    ports:
      - '9094:9094'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  mongo-data:
    driver: local
